name: Staging deployment check

on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]

jobs:
  prevent_merge:
    name: Prevent Merge
    runs-on: ubuntu-latest
    steps:
      - name: Check for doc label
        run: |
          has_documentation = ${{ contains(github.event.pull_request.labels.*.name, 'documentation') }}
          if [[ "$has_documentation" ]]; then
            exit 0
          else
            exit 1
          fi
